### PR TITLE
pdf from buffer

### PR DESCRIPTION
**Pull request by magicode**

### CODE REVIEW

**Comment by blackbeam** [comment]
Hi! Thanks for contribution.

It looks like tests fails on your changes. Could you please look into errors?
To run tests locally execute this commands in repo's root:
```bash
npm install # to rebuild
npm test # to run tests
```

**Comment by magicode** [comment]
i fixed it.

**Comment by blackbeam** [comment]
And one more issue.
Please reindent with 4 spaces per indentation level.

**Comment by blackbeam** [comment]
Thanks.
Will publish asap.

**Comment by blackbeam** [comment]
Can't publish.
Looks like `MemStream` is unstable on linux.
Need more spare time to investigate this..

**Comment by blackbeam** [comment]
Published as v0.2.3

**Comment by magicode** [comment]
Thank you very much.

**Pull request merged**
